max_seq_length: 256
optimizer: "AdamW"  # "SGD", "AdamW"
learning_rate: 1e-3  # 1e-4, 1e-3, 1e-2
beta: 2
batch_size: 50
batch_accum_size: 60
track_every_step: true
project_name: "embed_training"
entity_name: "timur-galimzyanov"
